#!/usr/bin/env bash
# Regenerate crates/rekt-server/assets/demo_seed.sql — the baked snapshot the
# public demo (REKT_DEMO=1) restores on boot and on its periodic reseed.
#
# It builds a curated portfolio in a scratch DB, lets candles backfill from the
# live feed, runs the REAL analyst (CLI backend) to produce genuine briefing /
# weekly-review / market-brief / market-ideas output, then dumps the seedable
# tables (NOT candles/snapshots — those refetch live on the demo host).
#
# Usage:  FINNHUB_API_KEY=… ./scripts/gen_demo_seed.sh
set -euo pipefail
cd "$(dirname "$0")/.."

PORT=7790
DB=/tmp/rekt-seedgen/seed.db
OUT=crates/rekt-server/assets/demo_seed.sql
BASE="http://localhost:$PORT"
rm -rf /tmp/rekt-seedgen && mkdir -p /tmp/rekt-seedgen

cargo build -p rekt-server >/dev/null 2>&1

REKT_DB="$DB" REKT_LISTEN="127.0.0.1:$PORT" REKT_ANALYST_BACKEND=cli \
  REKT_AI_DAILY_BUDGET=50 RUST_LOG=rekt_server=warn \
  ./target/debug/rekt > /tmp/rekt-seedgen/server.log 2>&1 &
SRV=$!
trap 'kill $SRV 2>/dev/null || true' EXIT
for i in $(seq 1 30); do curl -sf "$BASE/api/health" >/dev/null 2>&1 && break; sleep 0.5; done

tx() { # kind symbol qty price ts
  curl -sf -X POST "$BASE/api/transactions" -H 'content-type: application/json' \
    -d "{\"kind\":\"$1\",\"symbol\":$2,\"qty\":$3,\"price\":$4,\"ts\":\"$5\"}" >/dev/null
}
echo "→ seeding portfolio…"
tx deposit null 0 150000 "2024-08-01T14:30:00Z"
tx buy '"AAPL"'  80 218 "2024-08-15T14:30:00Z"
tx buy '"MSFT"'  40 415 "2024-09-10T14:30:00Z"
tx buy '"NVDA"' 150 121 "2024-10-01T14:30:00Z"
tx buy '"GOOGL"' 60 178 "2024-11-12T14:30:00Z"
tx buy '"AMZN"'  35 220 "2025-01-15T14:30:00Z"
tx buy '"JPM"'   50 265 "2025-02-20T14:30:00Z"
tx buy '"XOM"'   90 108 "2025-03-10T14:30:00Z"
tx buy '"SPY"'   25 555 "2025-04-05T14:30:00Z"
tx buy '"VTI"'   30 285 "2025-05-15T14:30:00Z"
echo "→ watchlist + alerts…"
LID=$(curl -sf -X POST "$BASE/api/watchlists" -H 'content-type: application/json' \
  -d '{"name":"AI & Semis"}' | python3 -c "import sys,json;print(json.load(sys.stdin)['id'])")
curl -sf -X POST "$BASE/api/watchlists/$LID/symbols" -H 'content-type: application/json' \
  -d '{"symbols":"NVDA, AMD, TSM, AVGO, MU, SMCI, ARM, QCOM"}' >/dev/null
# Alerts are best-effort: one may be rejected if its condition is already met.
curl -sf -X POST "$BASE/api/alerts" -H 'content-type: application/json' \
  -d '{"symbol":"AAPL","condition":"price_below","threshold":"195","note":"add on a dip"}' >/dev/null || true
curl -sf -X POST "$BASE/api/alerts" -H 'content-type: application/json' \
  -d '{"symbol":"AMZN","condition":"price_below","threshold":"185","note":"scale in lower"}' >/dev/null || true

echo "→ classifying ETFs…"
python3 - "$DB" <<'PY'
import sqlite3,sys
c=sqlite3.connect(sys.argv[1]); c.execute("PRAGMA busy_timeout=8000")
c.execute("UPDATE instruments SET kind='etf' WHERE symbol IN ('SPY','VTI','QQQ','IWM','DIA')")
c.commit()
PY

echo "→ waiting for candle backfill (signals/screener need history)…"
sleep 45

run_wait() { # METHOD PATH  — start an analysis, poll until it leaves 'running'
  local id
  id=$(curl -sf -X "$1" "$BASE$2" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('id',''))" 2>/dev/null || true)
  echo "   started $2 (id=$id)"
  for i in $(seq 1 60); do
    sleep 3
    R=$(curl -sf "$BASE/api/analyst" | python3 -c "import sys,json;print('1' if not json.load(sys.stdin).get('running') else '0')")
    [ "$R" = "1" ] && break
  done
}
echo "→ running the real analyst (CLI)…"
run_wait POST "/api/analyst/briefing"
run_wait POST "/api/analyst/review"
run_wait POST "/api/market/brief"
run_wait POST "/api/screener/$LID/analyze"

echo "→ dumping seed → $OUT"
python3 - "$DB" "$OUT" <<'PY'
import sqlite3,sys
db,out=sys.argv[1],sys.argv[2]
c=sqlite3.connect(db); c.execute("PRAGMA busy_timeout=8000"); c.row_factory=sqlite3.Row
# Parents before children so the seed re-applies under FK enforcement.
# settings excluded: it only holds candle_floor:* backfill bookkeeping that must
# track the live-refetched candles, not the seed (see demo.rs SEED_TABLES).
TABLES=["instruments","transactions","watchlists","watchlist_members",
        "alerts","analyses","recommendations"]
def lit(v):
    if v is None: return "NULL"
    if isinstance(v,(int,)): return str(v)
    if isinstance(v,float): return repr(v)
    return "'"+str(v).replace("'","''")+"'"
lines=["-- GENERATED by scripts/gen_demo_seed.sh — do not edit by hand.",
       "-- The public demo (REKT_DEMO=1) restores this on boot + periodic reseed.",
       "-- Candles/snapshots are intentionally excluded (refetched live).",""]
for t in TABLES:
    cols=[r[1] for r in c.execute(f"PRAGMA table_info({t})")]
    rows=c.execute(f"SELECT * FROM {t}").fetchall()
    if not rows: continue
    collist=",".join(cols)
    # instruments is reference data kept across reseeds (not cleared); insert it
    # idempotently so a reseed doesn't PK-conflict on the existing rows.
    verb="INSERT OR IGNORE INTO" if t=="instruments" else "INSERT INTO"
    for r in rows:
        vals=",".join(lit(r[col]) for col in cols)
        lines.append(f"{verb} {t} ({collist}) VALUES ({vals});")
    lines.append("")
open(out,"w").write("\n".join(lines)+"\n")
print(f"   wrote {sum(1 for l in lines if l.startswith('INSERT'))} INSERT rows")
PY
echo "✓ done"
